// <auto-generated />
using System;
using FMS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FMS.Migrations
{
    [DbContext(typeof(FMSDbContext))]
    partial class FMSDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FMS.Models.LedgerCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.ToTable("LedgerCodes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Fuel",
                            Code = "DIESEL001",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Diesel - Service Trucks",
                            FuelType = "Diesel",
                            IsActive = true
                        },
                        new
                        {
                            Id = 2,
                            Category = "Fuel",
                            Code = "DIESEL002",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Diesel - Fuel Trailers",
                            FuelType = "Diesel",
                            IsActive = true
                        },
                        new
                        {
                            Id = 3,
                            Category = "Fuel",
                            Code = "DIESEL003",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Diesel - Underground Tanks",
                            FuelType = "Diesel",
                            IsActive = true
                        },
                        new
                        {
                            Id = 4,
                            Category = "Fuel",
                            Code = "PETROL001",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Petrol - Service Vehicles",
                            FuelType = "Petrol",
                            IsActive = true
                        },
                        new
                        {
                            Id = 5,
                            Category = "Fuel",
                            Code = "PETROL002",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Petrol - Underground Tanks",
                            FuelType = "Petrol",
                            IsActive = true
                        },
                        new
                        {
                            Id = 6,
                            Category = "Sundries",
                            Code = "SUNDRY001",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sundries - Lubricants",
                            FuelType = "",
                            IsActive = true
                        },
                        new
                        {
                            Id = 7,
                            Category = "Sundries",
                            Code = "SUNDRY002",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sundries - Maintenance",
                            FuelType = "",
                            IsActive = true
                        },
                        new
                        {
                            Id = 8,
                            Category = "Sundries",
                            Code = "SUNDRY003",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sundries - Cleaning",
                            FuelType = "",
                            IsActive = true
                        },
                        new
                        {
                            Id = 9,
                            Category = "Contract",
                            Code = "CONTRACT01",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Amplant Contract",
                            FuelType = "",
                            IsActive = true
                        },
                        new
                        {
                            Id = 10,
                            Category = "Contract",
                            Code = "CONTRACT02",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Musina Contract",
                            FuelType = "",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("FMS.Models.MeterReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlantNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ReadingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReadingType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ReadingValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TakenBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PlantNumber");

                    b.HasIndex("ReadingDate");

                    b.HasIndex("PlantNumber", "ReadingDate");

                    b.ToTable("MeterReadings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "",
                            PlantNumber = "FSH01-01",
                            ReadingDate = new DateTime(2023, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReadingType = "Initial",
                            ReadingValue = 5000m,
                            TakenBy = "System",
                            Unit = "Kilometers",
                            VehicleId = ""
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "",
                            PlantNumber = "FSH02-01",
                            ReadingDate = new DateTime(2023, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReadingType = "Initial",
                            ReadingValue = 7500m,
                            TakenBy = "System",
                            Unit = "Kilometers",
                            VehicleId = ""
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "",
                            PlantNumber = "FSH03-01",
                            ReadingDate = new DateTime(2023, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReadingType = "Initial",
                            ReadingValue = 3000m,
                            TakenBy = "System",
                            Unit = "Kilometers",
                            VehicleId = ""
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "",
                            PlantNumber = "FSH04-01",
                            ReadingDate = new DateTime(2023, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReadingType = "Initial",
                            ReadingValue = 6200m,
                            TakenBy = "System",
                            Unit = "Kilometers",
                            VehicleId = ""
                        });
                });

            modelBuilder.Entity("FMS.Models.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Capacity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CurrentStock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlantId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PlantName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PlantId")
                        .IsUnique();

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 2000m,
                            Category = "service_trucks",
                            CurrentStock = 1500m,
                            FuelType = "Diesel",
                            LastUpdated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedBy = "System",
                            Location = "Main Yard",
                            PlantId = "FSH01-01",
                            PlantName = "FSH01 - 01"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 2000m,
                            Category = "service_trucks",
                            CurrentStock = 1800m,
                            FuelType = "Diesel",
                            LastUpdated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedBy = "System",
                            Location = "Main Yard",
                            PlantId = "FSH02-01",
                            PlantName = "FSH02 - 01"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 2000m,
                            Category = "service_trucks",
                            CurrentStock = 1200m,
                            FuelType = "Diesel",
                            LastUpdated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedBy = "System",
                            Location = "Main Yard",
                            PlantId = "FSH03-01",
                            PlantName = "FSH03 - 01"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 2000m,
                            Category = "service_trucks",
                            CurrentStock = 1900m,
                            FuelType = "Diesel",
                            LastUpdated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedBy = "System",
                            Location = "Main Yard",
                            PlantId = "FSH04-01",
                            PlantName = "FSH04 - 01"
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 10000m,
                            Category = "fuel_trailers",
                            CurrentStock = 5000m,
                            FuelType = "Diesel",
                            LastUpdated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedBy = "System",
                            Location = "Trailer Park",
                            PlantId = "SLD02",
                            PlantName = "SLD 02"
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 10000m,
                            Category = "fuel_trailers",
                            CurrentStock = 7500m,
                            FuelType = "Diesel",
                            LastUpdated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedBy = "System",
                            Location = "Trailer Park",
                            PlantId = "SLD07",
                            PlantName = "SLD 07"
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 10000m,
                            Category = "fuel_trailers",
                            CurrentStock = 3000m,
                            FuelType = "Diesel",
                            LastUpdated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedBy = "System",
                            Location = "Trailer Park",
                            PlantId = "SLD09",
                            PlantName = "SLD 09"
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 50000m,
                            Category = "underground_tanks",
                            CurrentStock = 15000m,
                            FuelType = "Diesel",
                            LastUpdated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedBy = "System",
                            Location = "Underground Storage",
                            PlantId = "UDT49",
                            PlantName = "UDT 49"
                        },
                        new
                        {
                            Id = 9,
                            Capacity = 50000m,
                            Category = "underground_tanks",
                            CurrentStock = 25000m,
                            FuelType = "Petrol",
                            LastUpdated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedBy = "System",
                            Location = "Underground Storage",
                            PlantId = "UPT49",
                            PlantName = "UPT 49"
                        },
                        new
                        {
                            Id = 10,
                            Capacity = 50000m,
                            Category = "underground_tanks",
                            CurrentStock = 18000m,
                            FuelType = "Diesel",
                            LastUpdated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedBy = "System",
                            Location = "Underground Storage",
                            PlantId = "UDT890",
                            PlantName = "UDT 890"
                        },
                        new
                        {
                            Id = 11,
                            Capacity = 50000m,
                            Category = "underground_tanks",
                            CurrentStock = 22000m,
                            FuelType = "Diesel",
                            LastUpdated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedBy = "System",
                            Location = "Underground Storage",
                            PlantId = "STD02",
                            PlantName = "STD 02"
                        },
                        new
                        {
                            Id = 12,
                            Capacity = 50000m,
                            Category = "underground_tanks",
                            CurrentStock = 19000m,
                            FuelType = "Petrol",
                            LastUpdated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedBy = "System",
                            Location = "Underground Storage",
                            PlantId = "STD05",
                            PlantName = "STD 05"
                        });
                });

            modelBuilder.Entity("FMS.Models.Transactions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AttendantId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AttendantName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contract")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ConvertBy")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ConvertQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CurrentMeterReading")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CustomContract")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FuelStoreCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("InStock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IssueUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LedgerCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MeterUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlantNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("PreviousMeterReading")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Station")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StockItem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StockUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Store")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Vat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VatType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AttendantId");

                    b.HasIndex("LedgerCode");

                    b.HasIndex("PlantNumber");

                    b.HasIndex("TransactionDate");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("FMS.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Station")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@fms.com",
                            FullName = "Admin User",
                            IsActive = true,
                            PasswordHash = "$2a$11$CP/KMnsNmEog8GNUe9n8ieG8H8l0YP.RpTWUj.hcmHmrLpgz1c1o.",
                            Role = "admin",
                            Station = "Main Depot"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "attendant@fms.com",
                            FullName = "Attendant User",
                            IsActive = true,
                            PasswordHash = "$2a$11$P96igEL9YWv8Zt7dU3PGjO3jNU23.RNOo5yncfnGz3/koRVaik9M6",
                            Role = "attendant",
                            Station = "Main Depot"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
